### ISSUE TITLE
Issues and Clarifications on Installing the python files to test RL aspects of the Project

### ISSUE THREAD

**Issue by HarshithaBR** [empriselab/RCareWorld#27]
We are trying to set up the RCareWorld project in our Ubuntu 22.04.3 LTS machine

-  Upon starting the minimum install for the project, we noticed that the folder <pyrfuniverse_rcare> was missing in the git repository, and hence the project structure is different. [Minimum Install](https://sunny-building-1e7.notion.site/Install-the-Modules-3da89a0199ef481386d002b5997d623f)

    Also, we wanted to test the Full installation, and have submitted a request for the Unity files via the Google form. Can we have access to the test_install.sh file mentioned in the installation steps, as it seems to be missing in the repository? [Full Install](https://sunny-building-1e7.notion.site/Install-the-Modules-014832fa7896462893ce332cf8e70a7f)
 
-  We wanted to run the demo trajectories using : `python run.py <Env_Name> -u True` [Run Demo Environments](https://sunny-building-1e7.notion.site/Run-demo-environments-a5103c0ab6444aa188606b51a2dee9a0)
   Can we get any links to documentations, and resources regarding how the environment is to be set up?

    Also, what is the expectation from the "demo_interactive" function to be implemented in the environment? 

-  If we run `python run.py`, we are getting the following error:

```
`Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from pyrcareworld.envs import *
  File "/home/harshitha07/Documents/RCareWorldFullInstallation/rcareworld_workspace/rcare_py/pyrcareworld/pyrcareworld/envs/__init__.py", line 1, in <module>
    from .base_env import RCareWorld, RCareWorldGymWrapper
  File "/home/harshitha07/Documents/RCareWorldFullInstallation/rcareworld_workspace/rcare_py/pyrcareworld/pyrcareworld/envs/base_env.py", line 1, in <module>
    from gym.utils import seeding
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/site-packages/gym/__init__.py", line 13, in <module>
    from gym.envs import make, spec, register
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/site-packages/gym/envs/__init__.py", line 10, in <module>
    _load_env_plugins()
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/site-packages/gym/envs/registration.py", line 276, in load_env_plugins
    fn = plugin.load()
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/site-packages/gym_minigrid/__init__.py", line 5, in <module>
    from gym_minigrid import minigrid, roomgrid, wrappers
  File "/home/harshitha07/anaconda3/envs/rcarefull/lib/python3.8/site-packages/gym_minigrid/minigrid.py", line 86, in <module>
    class MissionSpace(spaces.Space[str]):
TypeError: 'type' object is not subscriptable`
```
  Can you please suggest how we can resolve these issues and proceed?

Thanks and Regards

**Comment by kavikode** [comment]
installing all the packages in a virtual environment seems important.

**Comment by DanielTakeshi** [comment]
@YoruCathy just wondering if this issue is under active exploration? Thank you very much!
